name: learnu actions pipeline
on: 
  push:
    branches: [master]
jobs:
  deploy:
     runs-on: ubuntu-latest
     steps:
      - uses: hashicorp/setup-terraform@v1

      - run: terraform init

      - id: plan
        run: terraform plan -no-color

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}
